version: "3.9"

services:

  backend:
    build: ./Backend
    container_name: kradfly_backend
    restart: always

    ports:
      - "3200:3200"

    env_file:
      - ./Backend/.env

  frontend:
    build: ./Frontend
    container_name: kradfly_frontend
    restart: always

    ports:
      - "6100:80"

    depends_on:
      - backend