version: "3.9"

services:

  backend:
    build: ./Backend
    container_name: kradfly_backend
    restart: always

    ports:
      - "7200:3100"

    env_file:
      - ./Backend/.env

  frontend:
    build: ./Frontend
    container_name: kradfly_frontend
    restart: always

    ports:
      - "6200:80"

    depends_on:
      - backend